[dugout]
version = "0.1.7"
recipients_hash = "f983c12efcec510054e8addcc4a98d30e1533ec9c91ad83b2c96a22ec59e6cc1"

[recipients]
rdekovich = "age1eljqzcp67yan0wreuqdr8k0n62a90hvpusmw3x30xmh6p4hmeq3saku7v6"

[secrets]
OPENAI_API_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdkNYalBDeHNFZk1hTW9p
ZXpHVnlGWGhuOFVnaUtOK0ZIaEhPcld5NFM0ClB2dUJkQ1pOTys5bjJrcG8wT1Zw
QjU4bk95RnJiMXk5Y0lGVzExNEVoNkkKLT4gUE0nTlN7KWotZ3JlYXNlCko3T0Z0
LzA5UDhWSnJOT3R5MWl6dEt4cTkxTDYvQkFxZEJGTHdlUVY1aXhpZTdBCi0tLSBm
Ukx5eERvcnZVdFFaL3pjNVlaRDNqMWlPeHNJa3JPdHZkTCsvUFo5Y3l3Cg75izuQ
5mU06H42ZFuuGoX0Nq09ARkrPq91YXZh67IAXNXSv6Fz5F+sePZiqmgT8UcAcq/B
U2HHuk6LUagcq3eJKYjyPTarHb4o8pn1ifYXVP4kmzIs+BjqLnbBUN2rzEy/0bkU
Zep/jf1rSHhxjIi5Qa5OiDET1llY0HRHKeWpwjQkJeqyiKlbi6qu31BS0ECY4G2n
eEgMuodDWHqAOrYvRIOXLBj/I4Mm/VdDV/yMbVdTAJZPzmRFRW2Op0H1Ubt7IZQ=
-----END AGE ENCRYPTED FILE-----
"""
TELEGRAM_BOT_TOKEN = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRG05QU5LVzNHb0RWMTdS
eFQ2MldtVmRYSGVMZ0RpWVN6ZlZ4RUZqTDBNCngzS004K3g1eU5LNFVsNWJzeW16
TGlPeDFodlA3RzN3T2lJcTgyaTNJUHMKLT4gYyMtZ3JlYXNlIDR2by4gTWEgIjFV
PDZ+IF53Wjt1Cjhoc3kzZHA5V3BMdXc1ajhZdGJOTHloNWlxMnZDRzNpY0tLaDQ5
bk01Q25IMnBJOUJoeE96SVppZWtldkRURQotLS0gZ0gzVElvMmh4SXhCU05oWFhO
OVhMS3BrRkNZT0NDbGszcHo2aWswZUtwNAov6t7XjPlAoA5l/18LyW5lEs53wP19
Q27G7RqsYXSz7bQdPanx134ImKxbGiTqgtmpcicIjaUK9qoP9gMGyBefNPgleFNs
5gL4hMuQ1hY=
-----END AGE ENCRYPTED FILE-----
"""
TELEGRAM_CHAT_ID = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWkNPd3JsaENOS2JmRGdN
M2xZb0g0OTFjNy9GTTJ0T3NnZ1JQR3UvcHlRCnVlZU93blpuU3JGUkh6bGYrVi9a
bzB5L2VNQ2lnbHAyTlpSNENYMlRoYXMKLT4gZ2QyLWdyZWFzZSBtCkFkODI4cEx0
eE9RSmxIN25TZHFKZFZCM3JWWHU1Z1lVCi0tLSB6c0dtSmRjSVJDeGJDaXd0RnZB
MFAyOWR5aHMrcUZ3NzZRUnE2RDRkN0ZJCn1unS1JO9Dggy/nSQnJffRPdBnOblOb
lllqaOgdCZKV5zLdUBGgKskK7g==
-----END AGE ENCRYPTED FILE-----
"""
WALLET_PRIVATE_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTC82cUcvSEdQVWdFa0dC
bUR5N1VadzdhK3FreGN2QitTcjNObWQ3UG1ZCnpFUm1IbDlNNjluTmlFc2h6Znhk
OCtDV0h6eTdKa1o1NFRMVjVPU2o1cDgKLT4gSnFHRi9aey1ncmVhc2UgRyBydApO
UlNUbldBbzdhdlp2UkdWUXVlM3MzS09LbUJXWWZsUVhadEdNY2NKRFZsd25jYUt5
cnc2dG9BRXpkaDNkSWVOCjh6WUJQbXRCcWFOcml2N2x5WHIyYzBNeEY4eFVuSko0
MllMN2pUWDd1NkkrZ1BqNEtDT2NqWWowUXlEVnBRCi0tLSBUbFFWRXEyTklkN2ps
d1BDdTYzaWpoU05zTTZPM3dDaVN6WCszWXJNSEZ3CtjxEVVZJjN+NLaZ4dhbQPm6
rWH/RCQg+gw2VolCmd9SOO8W4yIuX/lKdxOOI/2A2q6S3WA47yYvubXDFeQKdmhM
e1g1CPHKBDEvR8U39W6aN8JoUhsNR1r+svfmXSQ7ow==
-----END AGE ENCRYPTED FILE-----
"""
