[dugout]
version = "0.1.7"
recipients_hash = "e12b59a16923ed2839fed8c3d950e8b04a06e8c938ec36dc4f3f3bd40e0d4640"

[recipients]
lon1 = "age1hwke7k3hgzuhhy2dt5heede6y7r2l2w3fku6y7n93pc85v26gylsuskeql"
rdekovich = "age1eljqzcp67yan0wreuqdr8k0n62a90hvpusmw3x30xmh6p4hmeq3saku7v6"

[secrets]
OPENAI_API_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUWxPOWxuTjJnR0VZVmgv
dm1uUURCTTRDaXRZd0tpT3NZOUl4aVhlcEhnCjMwNXBKRG5MZmNmQ3BIUEhraG5Z
Y1ZyOTExNlVQd2VjZWpYQXBONEUrTmcKLT4gWDI1NTE5IFlpS29kY0Q4blBkSld5
ZkMzZHd1RytjTHB3d2FIWTRad1haN2Zlb3JNemcKVEtWeTgvaXlrRGlZYzNIZ1ZW
d1dLTU1NdUZGaE1HZ0haTDZnblVwZ3c1QQotPiAlfUFeNFotZ3JlYXNlIEteZidN
aHY0IDZ+eSkgdzE/RVwKWXh5dDJZNVZQRG9mRWdYYjZ3Ci0tLSBlQmlhUDAzdGlH
NXlobW5kUFdHcW1kaWt5UHRkYStpSlo4NitEMkZBTWs4CsrROlZe2xHcwsFSiOzH
iQbNpOWj+1ekPEdjVKmrNgHQiHwbWIvE4f663YL/dIN8zKjiCUD0VXS8NPIMtfwX
sJFxd5f2bljtfZZPrJm223ZFbROvhbRbjQ5CLei9Xq8ZWaCp4ORhFeiP41Yubjh1
3pWrZ/5QIF7mcxqsKkWpKIN1+t/L7a8MRWjZArNYNLzw2OSF2vgHsJxO12Sd3X6O
5K097XcQh2qL0/eSf/ngO+slaPY8oNSoXcYzIvRvXgfILrluY3Y=
-----END AGE ENCRYPTED FILE-----
"""
TELEGRAM_BOT_TOKEN = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNEwyRVJ2YUNyOWdacE5H
WmVtU3BPNDc3cWJaSWV1MTVwVHZXME00bUhVCktXWE1IZXhMK2hYVC9YWWVnc0Rk
UzFpdkdrMnhDTldNVFhHbDdtTXkxRmsKLT4gWDI1NTE5IHFFcG13b3UzRzJHMzl1
bUZ3aXBWeXM4ZU52eWgrekxXZVgyM0IrdTdCa2MKTVhxbkdscEVjMTZNRVU5MkVh
Z2lwM2JFNEpYZllJZ0l3Y2ZMQ1A4U2EvNAotPiBrPCgtZ3JlYXNlIERdYTJLUyBs
eClnLyB6O1ohQCgiID1lMHwKQ2haK2dUUjlxcUE2UldtTE5FTllMbTBKWldlaytn
K2JvUnA3RzUvVngvTjJQbXF1Mmp3Q0xxUGhYc2VNZWY4dAo0anVWWTMrSW5QVjgy
YWRPT2kxZmVneUtPYVYvSVRjQ3BVSE1nbGpZTFFwaXFlczRZaDJZUFFTbG41L0t4
Znh6CgotLS0gN1kxNE1wczhoK0krQ3hKTFR1Zkh1b1AxRnZOL05OdmxxRlI0ZjJE
RUdDdwqcP12YdK8TOYSoUcAhsnw/g4iL1fVaHpEsB1js0BNbcnZ2/EjKmPT/7TRQ
A9+uxYyypkOy/K+wtZy/3JnH3khQfsVCwq1JGl4rdYnNwqg=
-----END AGE ENCRYPTED FILE-----
"""
TELEGRAM_CHAT_ID = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaURBTThKaldNTzBURjh0
NjVoVXNSVkV1T0p3RWx0Q0ZZaHYyTzBoK1I4ClNzcm42Ykp3amFDUWZzbFVyWHFy
WW45OEF3QmM3TG5MZmQvcEYyU3pMbE0KLT4gWDI1NTE5IGhRVVJsYXZxWVFkNlZI
aEo2UU5VZUhVems5VTBZa0ZCNEhVZlh3ei9zbVkKWThLV2VDZWF0dWpaU29kczVr
bzVEd0hSVEs3WFk4MWxYamY3ZVNSM24ySQotPiBkPiE8c3wtZ3JlYXNlID5Ocnp8
SiRuIHRDYDkKY3NWS0ttNy9UZHJrRzJuMG9KZUQzUXhmaGtRZ0VQclhtK2VTL3dJ
VEVPWTZFd3g0aFlRTWZZMlg5d09pOFJmMQpQNFRVQVFhdC9VYVNUckdJQUI0Z2k3
VUxIdFpzYWJJYlB0dWdPNEQ3OFkvZHFEQ2ZEZ00welljLzkvawotLS0gbWdGeEIy
OWFZV08wSVZtZDFva1MrOHJ0YUdrT25SRWcrWG5wSTMvVGZFZwozget3Y4aUJ26T
Upn8KLDOd7AHBl7/hhXM2DqPSZ//dqPt7FA8CQRhfS8=
-----END AGE ENCRYPTED FILE-----
"""
WALLET_PRIVATE_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU25CV0owMjljWlJGVktq
eTM2K0VIQUhWZ2l3dHJMR2Q0YXdHdmxJTVU4CjJKYkRVbG9WUnAwU3NTNzMydmxj
SmVlYzlNOURYWm5TcHExNU1Fa2dYREkKLT4gWDI1NTE5IHJUaGp2aSs1R2RRTWdF
WEgveGpVdnczUkRVRVNsNmJRaXVWbEZhUlJ3UjgKS2JoamRvb1NWNU9ScTVUbUJw
TmxiVmVWVFZGUjdkMmZ5ekRncmRuQklFMAotPiBbISIsYG1LQS1ncmVhc2UgZUpD
cWlrClRKM1FmWFF6WGcKLS0tIG4xQk9Pcjl6M01reWdwMU0rL2k5dmdmYXhxVnlj
T200dTRWd2Vnb1dsekEKoMEl791/hM6rihyMaD828+m1uQRDi4QK6TC/M+Y/uGFG
TNgq7DXHNxhvpRVM4HlgbsMNXRaDnUkUPVqTEUCeWqELgWhVl4hL0HUZviLS39f0
mmxSi61kjRt4mfECs5T+
-----END AGE ENCRYPTED FILE-----
"""
