[dugout]
version = "0.1.7"
recipients_hash = "72aa4457980b8626be7710a7043428b841676680d123d9e22faae9f7e9b06780"

[recipients]
root = "age1wru8zgryw3z75aw2ryfgv7jzn7dsqqw297cn8kgna7gf6c4wdezql23uqj"

[secrets]
ANTHROPIC_API_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV29zdkYrbzZablNRdGM3
bjAxMDdXS0R3ZndlZFVGbWJiYWJUa2NMRW1zCndzWjl2V0N4T3dvandGWCtoVXls
dnlVZzFvQXJPR1E3N2UrT0pwYzRzWnMKLT4gU3wtZ3JlYXNlIEhhIFVsXk1zekBz
IGNLZwpVcHZjeUdzCi0tLSBqTEsyelZhUkdMai8vK2tkT3BpeFNvOG5WeU53dThr
ZGM4aStRZFlmczFFCiJ0q3p9Q0frKXv4AZQg22MreZ8Dy7v+dFoOVgLwgkRfzY6q
vb2YifFGaWytTKx5O5pS5Uq92I6CsGl3lhR2mfHr5faJMSPz519mneyMp6btHrH+
24TYN0AFC52pdyWAEsjoeXlIYSEyOK5oC80orRb3730IbYwL0a67g/JKznU/YhEb
LI/t1+3Cxt0+
-----END AGE ENCRYPTED FILE-----
"""
OPENAI_API_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESis4YWtuZnIvMmwzbGQr
cW5IdHQ4TXBqdkVLY2VDZFVDa1pHdmRXR1FVCkt4Y0hDYy82WVU4cStiRzhOWGVP
bnVGNUhNR1VJMjVDUk5BdjZGVlFjYW8KLT4gal85LWdyZWFzZSBIRX1YSixVIDUz
NXg/S10oIHckYWIgbkV8CjNlc2d1OFlOM1ZVRHdMTG9XRGI2c2VHY0VvVEREdFV3
Z1lPblo5a2pNUjQzVGF2SldnSWVUWlNTa3NvQTNMMlkKSC9EWWxTb1JmTC96MHNV
c0luQldSUTZaNHZYblVKb2wxdmpzZVZoaTBSZDRhYUxnNDI0OAotLS0gM1Y5N3BC
bnlJT1NqU3BpWkRhc0RGejJySWtVUTh3N3BFY21FUm5FZjZzUQoc8cmMHaKTkuK/
20nP5UDm/mg8m7U2e2Y3fWznNF+XcLfW24Mut/dPZcuSNNdSGHrMpZl4yFJfLjRq
wivzXlAjxapWdLrqLAmWn5PHrK11p+8kWBPaUEE0O+9pE4eOiCg7wgXBSB3+jAiP
H7e2/q4sOt+23KI41HFqn9KB3SjSoAY3s+AONl4zmd3y/H73Pa2uSWQqWuc5L1eE
/CVW3Ua5ywstBwnc+EVjjT+a2nJJedw8wP8BpxfcPDQZWesZVkhj2fCd
-----END AGE ENCRYPTED FILE-----
"""
TELEGRAM_BOT_TOKEN = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VUNYbDQvTUxERXladUxm
M0ptU0tpd2dwU2RoSnJEQXp5ckJYUmg5YjJRCkx2clZuSDZRRC9wQzArcXhadi82
eVRiRDJ3clZCb09MQjFhVXRUUHg2TFEKLT4gWzd+LWdyZWFzZSB2dXNuMycgU3Ig
LjNOCnBvOVZESk9WWTdGblg2blM4eXczWi93MHREK05OWkp6QkpUVGl0Vjl5ZExw
ZkJ5ZEw3NmttUHdLTTJGN1ZIb1QKT2pSM2s5RHk5MlAvek5IVkhJT2RsU2RUczJj
Y3RoSGNHcUNoQjJvCi0tLSBjTVhFcWlQUTYyQ0oyR1BtOG91RHpFN04xUUUwUC9L
TjhlNXFxVng0emRrCsq7dahN6H3OYfrskNTZ4lxqgLk5PP/h8Y9pkJD3PuvJ2e9x
nRYwt0Qb2wA=
-----END AGE ENCRYPTED FILE-----
"""
TELEGRAM_CHAT_ID = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWS9uZEk5V1llVkU0UXBJ
VmVUNVVKTmpWbGFQd1dzY1VzMThMNVJIK25rClJadTZkQXEvdmIxWTg1LzY0Qy9O
N0hDYUpmRG52OGZJVmpKNXNxaW5scEUKLT4gYFgnR1R7JlktZ3JlYXNlICEKSFBK
QlZuWDllTVhRSDYwamdWMmdqVSt6a1dQK3B5dTdDTDBCVEhIaG1WeGxzaU9CTUV3
cSsxS3AKLS0tIHdqL0hMeTN0bEJBRGEvRHJ1SWxxYVZZMzJoSSs0czNHbUZVWmRi
aU5uWXMK2Ld3JBwEQAPdnM3zmuds8KUqfY9S27EHthBihgeGmZJPzcNsk/+PXCIA
PA==
-----END AGE ENCRYPTED FILE-----
"""
WALLET_PRIVATE_KEY = """
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNDRTcGxHWlNoWW5Yc1h3
aVcxaTR2TWNpNC9NOGlicFMvVUVnaXZlQ2drCkpvWE9HbFUwdE51RTRUeDVtUnZv
VWQ5KzJRQkZ2bVdsczRsZU1qUU5ZU1kKLT4gOnxKLy1ncmVhc2UgOF8xUiRIClVx
ZU1xZzNQWE1vQjU1UzBTbzhTSEVvSVRTc2FBQQotLS0gRWRCMm9sejh6S3ZEZlhr
RWdYMUxDNjhQU0IyaFVFTVc5Z2d2YUcwUnF2Ywp93W4T/+uAgsrSoYCg//ciCEs6
xzwXM0jsiSxc03Rs9g74JihwI9pMd1jr
-----END AGE ENCRYPTED FILE-----
"""
